using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entity
{
    /// <summary>
    /// Topic = içerik üretim sürecinin kök varlığı.
    /// Her Topic bir fikri, bağlamı ve üretim parametrelerini taşır.
    /// ScriptGenerator bu varlığı giriş olarak kullanır.
    /// </summary>
    public class Topic : BaseEntity
    {
        [Required]
        public int UserId { get; set; }

        [Required, MaxLength(64)]
        public string TopicCode { get; set; } = default!; // e.g. "topic-20251107-001"

        // ---- Kavramsal Alanlar ----
        [MaxLength(64)]
        public string? Category { get; set; }      // e.g. "funfact", "educational"

        [MaxLength(128)]
        public string? SubCategory { get; set; }   // e.g. "marine_life", "psychology"

        [MaxLength(128)]
        public string? Series { get; set; }        // e.g. "Nature Wonders"

        public string? Premise { get; set; }       // English core idea
        public string? PremiseTr { get; set; }     // Optional Turkish translation

        [MaxLength(32)]
        public string? Tone { get; set; }          // e.g. "curious", "informative"

        [MaxLength(64)]
        public string? RenderStyle { get; set; }   // e.g. "bright_doc", "cinematic_dark"

        [MaxLength(64)]
        public string? VoiceHint { get; set; }     // e.g. "calm narrator"

        [MaxLength(64)]
        public string? ScriptHint { get; set; }    // e.g. "explanatory", "storytelling"

        [MaxLength(256)]
        public string? PotentialVisual { get; set; } // e.g. "animated map zoom + counter ticking"

        public bool FactCheck { get; set; } = false;
        public bool NeedsFootage { get; set; } = false;

        public int Priority { get; set; } = 0;

        // ---- JSON Alanı ----
        [Column(TypeName = "nvarchar(max)")]
        public string? TopicJson { get; set; } // Full topic JSON as generated by AI or user input

        // ---- Üretim Durumu ----
        public bool AllowScriptGeneration { get; set; } = true;
        public bool ScriptGenerated { get; set; } = false;
        public DateTimeOffset? ScriptGeneratedAt { get; set; }

        // ---- İlişkilendirmeler ----
        [ForeignKey(nameof(Prompt))]
        public int? PromptId { get; set; }
        public Prompt? Prompt { get; set; }

        [ForeignKey(nameof(Script))]
        public int? ScriptId { get; set; }
        public Script? Script { get; set; }
    }
}